# Generated by Django 4.2.7 on 2025-05-27 22:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoption',
            options={'verbose_name': 'Adoção', 'verbose_name_plural': 'Adoções'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='ngo',
            options={'verbose_name': 'ONG', 'verbose_name_plural': 'ONGs'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterField(
            model_name='adoption',
            name='adoption_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='api.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(help_text='Idade em meses', verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=100, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('male', 'Macho'), ('female', 'Fêmea')], max_length=10, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponível para adoção'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='api.ngo', verbose_name='ONG'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], default='medium', max_length=10, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('other', 'Outro')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='review',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Avaliação de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
